config/routes.rb
Rails.application.routes.draw do

post '/guests/guest_sign_in', to: 'public/guests#new_guest'

#deviseは順番に注意
devise_for :users,skip: [:passwords], controllers: {
registrations: "public/registrations",
sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    #get 'homes/top'
    resources:genres, only:[:index, :create, :edit, :update, :destroy]

    resources:posts, only:[:index, :show, :edit, :update, :destroy] do
      resources:post_comments,only: [:index, :edit, :update]
    end

    resources:users, only:[:index, :show, :edit, :update]
  end

  patch 'users/withdraw' => 'public/users#withdraw', as: "withdraw"

  scope module: :public do
    resources:inquiries,only:[:new, :create]
    post 'inquiries/confirm'=> 'inquiries#confirm',as: "confirm"
    get 'inquiries/thanks' => 'inquiries#thanks',as: "thanks"

    root to: 'homes#top'
    get '/about' => 'homes#about', as: "about"

    resources:post_comments, only:[:index, :edit, :create, :destroy]

    resources:users, only:[:index, :show, :edit, :update] do
      member do
        get :myfavorites
      end
    end

    resources:post_images, only:[:index, :show, :new, :create, :destroy]

    resources:posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
      resources:post_comments,only: [:create]
      resource:favorites, only:[:create, :destroy]

      get :search, on: :collection
    end

  end
  get 'users/:id/unsubscribe' => 'public/users#unsubscribe', as: "unsubscribe"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

    def destroy
    @genre=Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div><h1><i class="fas fa-fan"></i>ジャンル編集</h1></div>
<div>
  <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
  <table>
    <tr>
      <td><h4>ジャンル名</h4></td>
      <td><%= f.text_field :name %></td>
      <td><%= f.submit '変更を保存' %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<h1><i class="fas fa-fan"></i>ジャンル一覧</h1>
<%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
  <div>
    <table>
      <tr>
        <th><h4>ジャンル名</h4></th>
        <td><%= f.text_field :name, placeholder: "新しいジャンルは？" %></td>
        <td><%= f.submit '新規登録' %></td>
      </tr>
    </table>
  </div>
<% end %>
<div>
  <table>
    <tr>
      <th></th>
    </tr>
    <% @genres.each do |genre| %>
    <tr>
      <td><h4><%= genre.name %></h4></td>
      <td><%= link_to '編集する', edit_admin_genre_path(genre.id) %></td>
      <td>|</td>
      <td><%= link_to '削除する', admin_genre_path(genre.id), method: :delete %></td>
    <% end %>
    </tr>

  </table>