config/routes.rb
Rails.application.routes.draw do

post '/guests/guest_sign_in', to: 'public/guests#new_guest'

#deviseは順番に注意
devise_for :users,skip: [:passwords], controllers: {
registrations: "public/registrations",
sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    #get 'homes/top'
    resources:genres, only:[:index, :create, :edit, :update, :destroy]

    resources:posts, only:[:index, :show, :edit, :update, :destroy] do
      resources:post_comments,only: [:index, :edit, :update]
    end

    resources:users, only:[:index, :show, :edit, :update]
  end

  patch 'users/withdraw' => 'public/users#withdraw', as: "withdraw"

  scope module: :public do
    resources:inquiries,only:[:new, :create]
    post 'inquiries/confirm'=> 'inquiries#confirm',as: "confirm"
    get 'inquiries/thanks' => 'inquiries#thanks',as: "thanks"

    root to: 'homes#top'
    get '/about' => 'homes#about', as: "about"

    resources:post_comments, only:[:index, :edit, :create, :destroy]

    resources:users, only:[:index, :show, :edit, :update] do
      member do
        get :myfavorites
      end
    end

    resources:post_images, only:[:index, :show, :new, :create, :destroy]

    resources:posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
      resources:post_comments,only: [:create]
      resource:favorites, only:[:create, :destroy]

      get :search, on: :collection
    end

  end
  get 'users/:id/unsubscribe' => 'public/users#unsubscribe', as: "unsubscribe"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many:favorites, dependent: :destroy
  has_many:tagmaps, dependent: :destroy
  has_many:tags, through: :tagmaps
  #ジャンルを複数設定したい場合は中間テーブルを作る
  has_one_attached :image
  has_many_attached :post_images

  validates:title, presence:true#タイトルは必須

  def get_photo(width, height)
    unless post_images.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      post_images.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type: 'image/jpeg')
    end
    post_images[0].variant(resize_to_limit:[width,height]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  #あいまい検索
  def self.search(keyword)
    where("title LIKE? OR body LIKE?", "%#{keyword}%","#{keyword}%")
  end

  def save_posts(tags)
    current_tags=self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    # Destroy
    old_tags.each do |old_name|
     self.tags.delete Tag.find_by(tag_name:old_name)
    end
    # Create
    new_tags.each do |new_name|
     post_tag=Tag.find_or_create_by(tag_name:new_name)
     self.tags << post_tag
    end
  end

enum post_status:{
    publish:0,
    unpublish:1,
    draft:2
  }

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  #def new
   #@post=Post.new
  #end

  #def create
    #@post=Post.new(post_params)
    #@post.user_id=current_user.id
    #@post.save
    #redirect_to posts_path
  #end

  def index
    @posts = Post.all
  end

  def show
    @post=Post.find(params[:id])
    #@post_comment=PostComment.find(params[:id])#0114ここに書くことではない、内容も誤り
  end

  def destroy
    @posts=Post.all
    @post=Post.find(params[:id])
    @post.destroy
    redirect_to admin_root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :user_id, :genre_id, :image, post_images:[])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>
<p>Find me in app/views/admin/posts/edit.html.erb</p>

app/views/admin/posts/show.html.erb
<h1>投稿詳細</h1>
<div><%= @post.created_at.strftime('%Y/%m/%d  %H:%M') %></div>
<div>
  <% if @post.post_images.attached? %>
    <% @post.post_images.each do |image| %>
      <%= image_tag image.variant(resize_to_limit:[150,150]).processed %>
    <% end %>
  <% else %>
    <%= image_tag 'no_image.jpg' %>
  <% end %>
</div>
<div>
  タイトル:<%= @post.title %>
</div>
<div>
  本文:<%= @post.body %>
</div>
<div>～以下コメント欄～</div>
<table>
  <tr>
    <td>コメント件数：<%= @post.post_comments.count %></td>
  </tr>
  <% @post.post_comments.each do |post_comment| %>
  <tr>
    <td>
    <%= image_tag post_comment.user.get_profile_image(50,50), class:"mt-3 rounded-circle"; %>
    <%= post_comment.comment %>
    <%= post_comment.user.nickname %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %>
    </td>
  </tr>
  <tr>
    <td>
      <%= form_with model: [@post,post_comment], url: admin_post_post_comment_path(@post.id,post_comment.id), method: :patch, local: true do |f| %>
        <%= f.radio_button:is_deleted, false %>
        <%= f.label:is_deleted, "OK", {value:false, style:"display:inline-box;"} %>
        <%= f.radio_button:is_deleted, true %>
        <%= f.label:is_deleted, "NG", {value:true, style:"display:inline-box;"} %>
        <%= f.submit "更新" %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>