config/routes.rb
Rails.application.routes.draw do

post '/guests/guest_sign_in', to: 'public/guests#new_guest'

#deviseは順番に注意
devise_for :users,skip: [:passwords], controllers: {
registrations: "public/registrations",
sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    #get 'homes/top'
    resources:genres, only:[:index, :create, :edit, :update, :destroy]

    resources:posts, only:[:index, :show, :edit, :update, :destroy] do
      resources:post_comments,only: [:index, :edit, :update]
    end

    resources:users, only:[:index, :show, :edit, :update]
  end

  patch 'users/withdraw' => 'public/users#withdraw', as: "withdraw"

  scope module: :public do
    resources:inquiries,only:[:new, :create]
    post 'inquiries/confirm'=> 'inquiries#confirm',as: "confirm"
    get 'inquiries/thanks' => 'inquiries#thanks',as: "thanks"

    root to: 'homes#top'
    get '/about' => 'homes#about', as: "about"

    resources:post_comments, only:[:index, :edit, :create, :destroy]

    resources:users, only:[:index, :show, :edit, :update] do
      member do
        get :myfavorites
      end
    end

    resources:post_images, only:[:index, :show, :new, :create, :destroy]

    resources:posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
      resources:post_comments,only: [:create]
      resource:favorites, only:[:create, :destroy]

      get :search, on: :collection
    end

  end
  get 'users/:id/unsubscribe' => 'public/users#unsubscribe', as: "unsubscribe"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates:last_name,presence: true
  validates:first_name,presence: true
  validates:nickname,presence: true,uniqueness: true,length:{minimum:2,maximum:20}
  validates:introduction,length:{maximum:140}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/syokubutsu_nae.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width,height]).processed
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @posts=@user.posts
  end
  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id),notice: "プロフィールを更新しました！"
    else
      render :edit
    end
  end

  private
  def user_params
      params.require(:user) .permit(:email, :encrypted_password, :last_name, :first_name,
                                      :nickname, :introduction, :profile_image, :is_deleted)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h2><i class="fas fa-fan"></i>会員情報編集<悪用厳禁></h2>

<%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>

  <div class="field">
    <label for="inputName">姓</label></br>
    <%= f.text_field :last_name, id:"inputName", placeholder:"姓"%></br>
  </div>

  <div class="field">
    <label for="inputName">名</label></br>
    <%= f.text_field :first_name, id:"inputName", placeholder:"名"%></br>
  </div>

  <div class="field">
    <label for="inputName">ニックネーム</label></br>
    <%= f.text_field :nickname, id:"inputName", placeholder:"ニックネーム" %></br>
  </div>

  <div class="field">
    <label for="inputName">自己紹介</label></br>
    <%= f.text_field :introduction, id:"inputName", placeholder:"自己紹介"%></br>
  </div>

  <label for="inputImage">プロフィール画像</label></br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  </br>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div>
    <%= f.label:is_deleted, "有効", {value:false, style:"display:inline-box;"} %>
    <%= f.radio_button:is_deleted, false %>
    <%= f.label:is_deleted, "退会", {value:true, style:"display:inline-box;"} %>
    <%= f.radio_button:is_deleted, true %>
  </div>

  <div class="actions">
    <%= f.submit "更新する" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1><i class="fas fa-fan"></i>会員一覧</h1>
<% @users.each do |user| %>
<table>
  <tr>
    <td><%= image_tag user.get_profile_image(40,40) %></td>
    <td>
      <%= link_to admin_user_path(user.id) do %>
        <%= user.nickname %>
      <%end%>
      （<%= user.posts.count %>件の投稿）
    </td>
    <td>会員ステータス:
      <% if user.is_deleted==false %>
        有効
      <% else %>
        退会
      <% end %>
    </td>
    <td><%#= user.introduction %></td>
  </tr>
</table>
<%end%>

app/views/admin/users/show.html.erb
<h1><i class="fas fa-fan"></i>会員情報詳細</h1>

<table>
  <tr>
    <td><%= image_tag @user.get_profile_image(250,250) %></td>
  </tr>
  <tr><td>
    <%= link_to admin_user_path(@user.id) do %>
      <%= @user.nickname %>
    <%end%>
  </td></tr>
  <tr>
    <td><%= @user.introduction %></td>
  </tr>
  <tr>
    <td>
      <%# if @user==current_user %>
        <%= link_to"プロフィール詳細・編集",edit_admin_user_path(@user) %>
      <%#end%>
    </td>
  </tr>
</table>
～以下投稿履歴～
  <% @posts.each do |post| %>
    <table>
      <tr>
        <td>
          <%= link_to admin_post_path(post.id) do %>
            <%= post.title %>
          <%end%>
          <span>　</span>
          <i class="far fa-thumbs-up text-dark"></i><%= post.favorites.count %>
          <span>　</span>
          <i class="far fa-comment text-dark"></i><%= post.post_comments.count %>
        </td>
        <td>（<%= post.created_at.strftime('%Y/%m/%d') %>）</td>
      </tr>
    </table>
  <%end%>