config/routes.rb
Rails.application.routes.draw do

post '/guests/guest_sign_in', to: 'public/guests#new_guest'

#deviseは順番に注意
devise_for :users,skip: [:passwords], controllers: {
registrations: "public/registrations",
sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    #get 'homes/top'
    resources:genres, only:[:index, :create, :edit, :update, :destroy]

    resources:posts, only:[:index, :show, :edit, :update, :destroy] do
      resources:post_comments,only: [:index, :edit, :update]
    end

    resources:users, only:[:index, :show, :edit, :update]
  end

  patch 'users/withdraw' => 'public/users#withdraw', as: "withdraw"

  scope module: :public do
    resources:inquiries,only:[:new, :create]
    post 'inquiries/confirm'=> 'inquiries#confirm',as: "confirm"
    get 'inquiries/thanks' => 'inquiries#thanks',as: "thanks"

    root to: 'homes#top'
    get '/about' => 'homes#about', as: "about"

    resources:post_comments, only:[:index, :edit, :create, :destroy]

    resources:users, only:[:index, :show, :edit, :update] do
      member do
        get :myfavorites
      end
    end

    resources:post_images, only:[:index, :show, :new, :create, :destroy]

    resources:posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
      resources:post_comments,only: [:create]
      resource:favorites, only:[:create, :destroy]

      get :search, on: :collection
    end

  end
  get 'users/:id/unsubscribe' => 'public/users#unsubscribe', as: "unsubscribe"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many:favorites, dependent: :destroy
  has_many:tagmaps, dependent: :destroy
  has_many:tags, through: :tagmaps
  #ジャンルを複数設定したい場合は中間テーブルを作る
  has_one_attached :image
  has_many_attached :post_images

  validates:title, presence:true#タイトルは必須

  def get_photo(width, height)
    unless post_images.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      post_images.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type: 'image/jpeg')
    end
    post_images[0].variant(resize_to_limit:[width,height]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  #あいまい検索
  def self.search(keyword)
    where("title LIKE? OR body LIKE?", "%#{keyword}%","#{keyword}%")
  end

  def save_posts(tags)
    current_tags=self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    # Destroy
    old_tags.each do |old_name|
     self.tags.delete Tag.find_by(tag_name:old_name)
    end
    # Create
    new_tags.each do |new_name|
     post_tag=Tag.find_or_create_by(tag_name:new_name)
     self.tags << post_tag
    end
  end

enum post_status:{
    publish:0,
    unpublish:1,
    draft:2
  }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_one_attached :image
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many:tagmaps, dependent: :destroy
  has_many:posts, through: :tagmaps

  #各ｺﾝﾄﾛｰﾗの@tag_lists=...を簡単な表記に変えたい
  def self.mapped(n=30)
    where(id:
     Tagmap.group(:tag_id).order('count(post_id) desc').limit(n).pluck(:tag_id)
    )
  end
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates:last_name,presence: true
  validates:first_name,presence: true
  validates:nickname,presence: true,uniqueness: true,length:{minimum:2,maximum:20}
  validates:introduction,length:{maximum:140}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/syokubutsu_nae.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width,height]).processed
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @posts=Post.all
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  #def new
   #@post=Post.new
  #end

  #def create
    #@post=Post.new(post_params)
    #@post.user_id=current_user.id
    #@post.save
    #redirect_to posts_path
  #end

  def index
    @posts = Post.all
  end

  def show
    @post=Post.find(params[:id])
    #@post_comment=PostComment.find(params[:id])#0114ここに書くことではない、内容も誤り
  end

  def destroy
    @posts=Post.all
    @post=Post.find(params[:id])
    @post.destroy
    redirect_to admin_root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :user_id, :genre_id, :image, post_images:[])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @posts=@user.posts
  end
  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id),notice: "プロフィールを更新しました！"
    else
      render :edit
    end
  end

  private
  def user_params
      params.require(:user) .permit(:email, :encrypted_password, :last_name, :first_name,
                                      :nickname, :introduction, :profile_image, :is_deleted)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_session_path
    elsif resource == :user
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :nickname])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%#= favicon_link_tag('favicon.ico') %>
    <title>Gardening</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

     <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <%#= favicon_link_tag %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              ようこそ、<%= current_user.nickname %>さん！
              <li class="nav-item">
                <%= link_to user_path(current_user.id),class: 'nav-link text-black' do %>
                  <i class="fas fa-user"></i>マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to posts_path,class: 'nav-link text-black' do %>
                  <i class="fas fa-book-open"></i>投稿一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path,class: 'nav-link text-black' do %>
                  <i class="fas fa-user-friends"></i>会員一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to root_path,class: 'nav-link text-black' do %>
                  <i class="fas fa-envelope"></i>工事中
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_post_path,class: 'nav-link text-black' do %>
                  <i class="fas fa-pen"></i>新規投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-black' do %>
                  <i class="fas fa-sign-out-alt"></i>ログアウト
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              管理者でログインしています
              <li class="nav-item">
                <%= link_to "投稿一覧", admin_root_path,class: 'nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_users_path,class: 'nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path,class: 'nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'nav-link text-black' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_session_path,class: 'nav-link text-black' do %>
                  <i class="fas fa-sign-in-alt"></i>ログイン
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to guests_guest_sign_in_path, method: :post,class: 'nav-link text-black' do %>
                  <i class="fas fa-user-secret"></i>ゲストログイン
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>

    <%= yield %>
  </body>
</html>